- hosts: localhost
  gather_facts: no
  name: Respond to Iptables being executed in a privileged container
  tasks:
  - name: Send Alert content to stdout
    debug:
      msg: "{{ alert }}"
  
  - name: Obtain Pod UID
    set_fact:
      pod_uid: "{{ alert.processViolation.processes[0].podUid }}"

  - name: Get audit log
    shell: >
      oc adm node-logs --role=master --path=kube-apiserver/audit.log | grep {{ pod_uid }}
    register: audit_log_output

  - name: Get User name
    set_fact:
      username: "{{ audit_log_output.stdout | regex_search('\"username\":\"([a-z0-9]+)\"', '\\1') | first }}"

  - name: Get ClusterRoleBindings
    shell: >
      oc get clusterrolebindings -o json | jq '[.items[] | select(has("subjects") and .subjects[].name=="{{ username }}")]'
    register: clusterrolebindings

  - name: Get RoleBindings
    shell: >
      oc get rolebindings -A -o json | jq '[.items[] | select(has("subjects") and .subjects[].name=="{{ username }}")]'
    register: rolebindings

  - name: Print out bindings to be removed
    debug:
      msg: |
        Removing the following bindings:
        
        {{ clusterrolebindings.stdout | from_json | to_nice_json }}

        {{ rolebindings.stdout | from_json | to_nice_json }}

  - name: Remove bindings
    k8s:
      state: absent
      definition: |
        {{ ( clusterrolebindings.stdout | from_json ) + ( rolebindings.stdout | from_json ) }}
