---
- name: Listen for ACS events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ eda_token }}"
  rules:
    - name: Revoke User Privileges
      condition: event.meta.headers is defined
      action:
        run_job_template:
          name: Revoke User Privileges
          organization: Default
          job_args:
            extra_vars:
              alert: "{{ event.payload.alert }}"