---
- name: Listen for ACS events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ eda_token }}"
  rules:
    - name: Run Job Template
      condition: event.payload.template_name is defined
      action:
        run_job_template:
          name: "{{ event.payload.template_name }}"
          organization: Default
          job_args:
            extra_vars:
              alert: "{{ event.payload.alert }}"