---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ eda_token }}"
  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.meta.headers is defined
  ## Define the action we should take should the condition be met
      action:
        run_job_template:
          name: Revoke User Privileges
          organization: Default
          job_args:
            extra_vars:
              alert: blah