apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-fake-miner
  namespace: crypto 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-fake-miner
  template:
    metadata:
      labels:
        app: real-fake-miner
    spec:
      containers:
      - name: real-fake-miner
        image: registry-old-image.apps.cluster-5rmld.5rmld.sandbox2205.opentlc.com/real-fake-crypto-miner:latest
        command: ["/bin/sh", "-c"]
        args: ["echo BEEP BOOP BEEP && echo \"Initiating top-secret, totally-legit, and definitely not \'cryptocurrency mining\' operation...\" && echo && echo && ./cpuminer/minerd -h && tail -f /dev/null"]
